{
    "name": "GIMA Partner",
    "author": "Luca D'Ambrosio",
    "website": "http://www.lucadambrosio.cloud",
    "license": "LGPL-3",
    "category": "Contacts",
    "version": "17.0.2.0.0",
    "depends": ["base", "contacts"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "views/gima_macro_course_views.xml",
        "views/res_partner_views.xml",
        "views/gima_course_views.xml",
        "views/gima_macro_certification_views.xml",
        "views/gima_certifications_views.xml",
        "views/gima_training_views.xml",
        "views/gima_promoter_views.xml",
        "views/account_portal_templates_views.xml",
        "views/reset_password_templates_email.xml",
        "views/mail_notification_light_template.xml",
        "views/gima_documents_views.xml",
    ],
}
